### ISSUE TITLE
Potential Bug : `space-FLAIR` vs `space-flair`

### ISSUE THREAD

**Issue by jqmcginnis** [CompImg/LST-AI#20]
Hey,

I just noticed that we are not using consistent `space-flair` vs `space-FLAIR` file name labels. Is this intentional to distinguish between the prob masks, or just an oversight?

Check the filenames here: https://github.com/CompImg/LST-AI/blob/2c350eb9688af5758969f29a1ff1a1f215f289bf/LST_AI/lst#L168

and e.g.:
https://github.com/CompImg/LST-AI/blob/2c350eb9688af5758969f29a1ff1a1f215f289bf/LST_AI/lst#L148

For backwards compatibility, I would likely keep the `space-flair` - or what do you think?

**Comment by twiltgen** [comment]
Hey, 
ohh yeah, I used space-FLAIR in the newly added lines for the probability map since I'm used to that convention. But feel free to change it back to space-flair :)

**Comment by mervinTEE** [comment]
hi, on the same topic of space. I am interested in using this pipeline for my research. However, I have a few questions regarding space. 

1) Does the "annotate only" convert the supplied WMH mask into MNI space?
2) For the full pipeline, is the quantification done after or before warping to MNI space? 
3) Is every file in the temp output MNI space? Or does it contain subject space, too?
4) Is there a way that we can concat all subject measurements as one csv?

**Comment by mervinTEE** [comment]
I just found the answers in #5 as one of your replies! So, I'm just left with (4) as my question!

> 1. Does the "annotate only" convert the supplied WMH mask into MNI space?
> 2. For the full pipeline, is the quantification done after or before warping to MNI space?
> 3. Is every file in the temp output MNI space? Or does it contain subject space, too?

**Comment by twiltgen** [comment]
Hi @mervinTEE ,

Thanks for reaching out! We're excited to hear that you're interested in using LST-AI. I hope I can clarify your questions:

1) When using the "--annotate_only" option, the process starts by registering the T1w image to the FLAIR image. Then, the atlas mask is registered to the T1w image (which is now aligned with the FLAIR space). The annotation is performed in this FLAIR space, resulting in annotated lesion masks in the FLAIR space (output as "sub-X_ses-Y_space-flair_desc-annotated_seg-lst.nii.gz"). Please note that when using the "--annotate_only" option, the lesion mask is not registered to MNI 

2) The toolbox generates lesion masks both in FLAIR space ("...space-flair_seg-lst.nii.gz") and MNI space ("...space-mni_seg-lst.nii.gz"). However, quantification is always performed in the FLAIR space.

3) The output in the temp folder includes files in both the subject's space and MNI space. The image space is specified after the "_space-" attribute. You are absolutely right—we updated the naming conventions because "space-orig" was unclear about whether it referred to the original T1w space or the original FLAIR space. Now, we use "space-flair," "space-t1w," and "space-mni" to specify the image space clearly.

4) Currently, lesion data is only available on a per-subject basis. The tool doesn’t yet include a feature to aggregate data from the CSV files of all subjects, but this should be relatively straightforward to implement. And of course, we’d welcome any contributions if you think adding this feature would be helpful!

I hope this answers your questions!

Best,
Tun
