### ISSUE TITLE
Lesion masks are not in the same space as native flair images nor MNI space

### ISSUE THREAD

**Issue by AABayoumi** [CompImg/LST-AI#5]
Hi Julian,

Thanks for your efforts working on LST and LST-AI. The instructions you provided were really helpful to ensure a seamless setup. I am having a slight issue though, for some reason the lesion masks created are not in the native FLAIR images space nor are they in standard mni space. Do you have any suggestions to resolve this issue?

Best,
Ahmed

**Comment by AABayoumi** [comment]
I ran a different scan and it is working now, sorry for the inconvenience!

Thanks,
Ahmed

**Comment by jqmcginnis** [comment]
@AABayoumi Thank you very much for checking out LST-AI and for your feedback, and I am sorry that you are experiencing some problems.

To debug your errors, could you please share the following information with me? :slightly_smiling_face: 

1. Which platform and codebase are you using? Are you working under linux with native python implementation or are you running everything in docker?

2. With respect to the lesion maps, can you let me know which images / masks you are specifically loading (i.e. exact names) as image and which as lesion maps? Are you using the `--temp` option to preserve all processed files?

Another user asked me for a detailed explanation of all files, so there might be some room for misunderstandings, I am copying the description to this issue as well:

_LST.AI performs segmentation and annotation in the MNI152 template space. For users that would like to keep the registered T1w and FLAIR images and their corresponding segmentation masks, we allow to keep these files if the user provides a temp directory. If you skip the `--temp` option, then LST-AI will create and delete the temp folder for you (and the temp files vanish)._
```
├── affine_flair_to_mni.mat --> Registration Matrix obtained via greedy
├── affine_t1w_to_mni.mat --> Registration Matrix obtained via greedy
├── atlas_mask_warped.nii.gz --> Deformation Field obtained via greedy for annotation of lesions acc. to McD criteria
├── atlas_warp_field.nii.gz --> Deformation Field obtained via greedy for annotation of lesions acc. to McD criteria
├── sub-X_ses-Y_space-mni_brainmask.nii.gz --> Brain Mask in MNI space
├── sub-X_ses-Y_space-mni_desc-stripped_FLAIR.nii.gz --> Skull-stripped FLAIR in MNI
├── sub-X_ses-Y_space-mni_desc-stripped_T1w_mask.nii.gz --> Brainmask T1w in MNI space
├── sub-X_ses-Y_space-mni_desc-stripped_T1w.nii.gz --> Skull-stripped T1w 
├── sub-X_ses-Y_space-mni_FLAIR.nii.gz --> FLAIR in MNI space (with skull)
├── sub-X_ses-Y_space-mni_seg-annotated.nii.gz --> Anno. Seg. in MNI Space
├── sub-X_ses-Y_space-mni_seg.nii.gz --> Binary Segmentation in MNI Space
├── sub-X_ses-Y_space-mni_T1w.nii.gz --> T1w (with skull) in MNI Space
├── sub-X_ses-Y_space-org_FLAIR_mask.nii.gz --> Brainmask in Native Space
├── sub-X_ses-Y_space-org_T1w_mask.nii.gz --> Brainmask T1w in Native Space
├── sub-X_ses-Y_space-orig_desc-stripped_FLAIR.nii.gz --> Stripped FLAIR in native space
├── sub-X_ses-Y_space-orig_desc-stripped_T1w.nii.gz --> Stripped FLAIR in native space
├── sub-X_ses-Y_space-orig_FLAIR.nii.gz --> copy of orig. FLAIR
├── sub-X_ses-Y_space-orig_seg-annotated.nii.gz --> output result: Ann. Seg. in native FLAIR space 
├── sub-X_ses-Y_space-orig_seg.nii.gz --> output result: Binary Seg. in FLAIR space
└── sub-X_ses-Y_space-orig_T1w.nii.gz --> copy of T1w 
```
Lastly, if you would be able to share an image (e.g. via mail), I would be able to take a look (however I know that due to privacy reasons this is not always feasible).

Kind regards,
Julian

**Comment by jqmcginnis** [comment]
@AABayoumi was this issue resolved? :slightly_smiling_face:
